apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: ${MONGO_USER} # Substitua pelo seu valor codificado em Base64
  mongo-password: ${MONGO_PASSWORD} # Substitua pelo seu valor codificado em Base64
